String.prototype.giveLydiaPizza = () => {
    return 'Just give Lydia pizza already!';
};

const name = 'Lydia';

console.log(name.giveLydiaPizza())              // Just give Lydia pizza already!


/*
String is a built-in constructor, that we can add properties to. 
I just added a method to its prototype. 
Primitive strings are automatically converted into a string object, generated by the string prototype function. 
So, all strings (string objects) have access to that method!
*/